# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 11:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043f\u0443\u043d\u043a\u0442\u0430 \u043c\u0435\u043d\u044e')),
                ('url', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': '\u041f\u0443\u043d\u043a\u0442 \u041c\u0435\u043d\u044e',
                'verbose_name_plural': '\u041f\u0443\u043d\u043a\u0442\u044b \u041c\u0435\u043d\u044e',
            },
        ),
        migrations.CreateModel(
            name='MenuGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043c\u0435\u043d\u044e')),
            ],
            options={
                'verbose_name': '\u041c\u0435\u043d\u044e',
                'verbose_name_plural': '\u041c\u0435\u043d\u044e',
            },
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.MenuGroup'),
        ),
        migrations.AddField(
            model_name='menu',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.Menu', verbose_name='\u0420\u043e\u0434\u0438\u0442\u0435\u043b\u044c\u0441\u043a\u0438\u0439 \u043f\u0443\u043d\u043a\u0442'),
        ),
    ]
